Support for API Token authentication
AsBuiltReport/AsBuiltReport.Rubrik.CDM pull request #20
Opened 2022-01-12 14:33 UTC by mwpreston

This PR adds support to connect to Rubrik clusters using API tokens rather than credential or Username/Password combinations.

## Description
A check is implemented before connecting to the Rubrik Cluster to detect whether Token or Credential based authentication was passed, and the proper parameters are passed.

## Motivation and Context
Many Rubrik customers have now implemented MFA on their clusters, which essentially removes the ability to connect to a rubrik cluster with the Powershell SDK using a Username/Password. This allows them to follow Rubrik best practices and generate API tokens for authentication with their automation scripts/toolsets.

## How Has This Been Tested?
This has been tested against Rubrik 5.0 and above and is working without issues.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.

2022-02-02 06:33 UTC, tpcarman commented on Src/Public/Invoke-AsBuiltReport.Rubrik.CDM.ps1
>          [String]$StylePath
$StylePath should no longer be required.

2022-02-02 06:35 UTC, tpcarman requested changes
Remove `$StylePath` parameter and you should be good to go.

2022-02-02 06:57 UTC, tpcarman commented on Src/Public/Invoke-AsBuiltReport.Rubrik.CDM.ps1
>          [String]$StylePath
Will also need to update the `RequiredModules` in the module manifest to 
```
RequiredModules = @(
        @{
            ModuleName = 'AsBuiltReport.Core';
            ModuleVersion = '1.2.0'
        }
    )
```

2022-02-03 14:37 UTC, mwpreston commented
@tpcarman removed StylePath, Updated RequiredModules  and Added Release.yml.  Do you mind having another quick look?

2022-02-03 20:00 UTC, merged